import type { PipelineLayer } from '@hudai/shared';

export function getDemoPipelines(): PipelineLayer {
  return {
    pipelines: [
      // --- Pipeline 1: Event Ingestion ---
      {
        id: 'event-ingestion',
        label: 'Event Ingestion Pipeline',
        category: 'event-driven',
        description: 'Captures agent activity from tmux polling and JSONL transcripts, translates into structured AVP events, persists to SQLite, and broadcasts via WebSocket.',
        blocks: [
          {
            id: 'tmux-capture',
            label: 'tmux capture-pane',
            blockType: 'source',
            files: ['packages/server/src/pty/agent-process.ts'],
            technology: 'tmux + Node.js child_process',
            description: 'Polls the tmux pane every 500ms using capture-pane, then applies anchor-based diffing to extract only new lines since the last poll. Outputs raw terminal text strings.',
          },
          {
            id: 'transcript-watcher',
            label: 'JSONL Transcript Watcher',
            blockType: 'source',
            files: ['packages/server/src/transcript/transcript-watcher.ts'],
            technology: 'Node.js fs.watch',
            description: 'Watches the Claude Code JSONL transcript file for appended lines using fs.watch. Emits raw JSONL entries as they are written by the agent process.',
          },
          {
            id: 'tmux-parser',
            label: 'Terminal Output Parser',
            blockType: 'transform',
            files: ['packages/server/src/parser/claude-code-parser.ts'],
            technology: 'Regex state machine',
            description: 'Parses Claude Code\'s rendered terminal format (⏺ ToolName, ❯ prompts, spinner chars) into structured AVP events using a regex-based state machine. Handles multi-line tool output and permission prompts.',
          },
          {
            id: 'jsonl-translator',
            label: 'JSONL → AVP Translator',
            blockType: 'transform',
            files: ['packages/server/src/transcript/jsonl-to-avp.ts'],
            technology: 'JSON parsing + type mapping',
            description: 'Translates Claude Code JSONL transcript entries into the AVP event protocol. Maps tool_use, tool_result, and assistant messages to file.read, file.edit, shell.run, and other AVP event types.',
          },
          {
            id: 'source-merge',
            label: 'Event Router',
            blockType: 'merge',
            files: ['packages/server/src/index.ts'],
            technology: 'Node.js EventEmitter',
            description: 'Merges AVP events from both the tmux parser and JSONL translator into a single stream. Deduplicates events that appear in both sources using event ID matching.',
          },
          {
            id: 'event-enrichment',
            label: 'Event Enrichment',
            blockType: 'transform',
            files: [
              'packages/server/src/index.ts',
              'packages/server/src/parser/loop-detector.ts',
              'packages/server/src/config/permission-stats.ts',
              'packages/server/src/transcript/token-tracker.ts',
            ],
            technology: 'Fastify server',
            description: 'Enriches raw AVP events with derived metadata: loop detection (repeated tool patterns), permission statistics tracking, and token usage accumulation. Attaches session context and sequence numbers.',
          },
          {
            id: 'sqlite-persist',
            label: 'SQLite Persistence',
            blockType: 'sink',
            files: [
              'packages/server/src/persistence/event-store.ts',
              'packages/server/src/persistence/db.ts',
            ],
            technology: 'better-sqlite3',
            description: 'Persists enriched AVP events to the global SQLite database at ~/.hudai/hudai.db. Stores events with session association for replay support. Uses WAL mode for concurrent read/write performance.',
          },
          {
            id: 'ws-broadcast',
            label: 'WebSocket Broadcast',
            blockType: 'sink',
            files: ['packages/server/src/index.ts'],
            technology: '@fastify/websocket',
            description: 'Broadcasts enriched AVP events to all connected WebSocket clients as JSON ServerMessage frames. Also sends graph updates, session state changes, and pipeline analysis results.',
          },
        ],
        edges: [
          { id: 'e1', source: 'tmux-capture', target: 'tmux-parser', label: 'raw terminal lines', edgeType: 'data' },
          { id: 'e2', source: 'transcript-watcher', target: 'jsonl-translator', label: 'JSONL entries', edgeType: 'data' },
          { id: 'e3', source: 'tmux-parser', target: 'source-merge', label: 'AVPEvent (tmux)', edgeType: 'data' },
          { id: 'e4', source: 'jsonl-translator', target: 'source-merge', label: 'AVPEvent (transcript)', edgeType: 'data' },
          { id: 'e5', source: 'source-merge', target: 'event-enrichment', label: 'AVPEvent', edgeType: 'data' },
          { id: 'e6', source: 'event-enrichment', target: 'sqlite-persist', label: 'enriched AVPEvent', edgeType: 'data' },
          { id: 'e7', source: 'event-enrichment', target: 'ws-broadcast', label: 'AVPEvent + side-effects', edgeType: 'data' },
        ],
      },

      // --- Pipeline 2: Client Rendering ---
      {
        id: 'client-rendering',
        label: 'Client Rendering Pipeline',
        category: 'state-management',
        description: 'Receives server messages via WebSocket, dispatches to Zustand stores, and drives the Canvas codebase map with real-time heat, activity overlays, and force-directed layout.',
        blocks: [
          {
            id: 'ws-client',
            label: 'WebSocket Client',
            blockType: 'source',
            files: ['packages/client/src/ws/ws-client.ts'],
            technology: 'Browser WebSocket',
            description: 'Singleton WebSocket client with auto-reconnect (2s backoff). Receives JSON ServerMessage frames and distributes them to registered handlers. Connects via Vite proxy at /ws.',
          },
          {
            id: 'store-dispatch',
            label: 'Store Dispatcher',
            blockType: 'branch',
            files: ['packages/client/src/hooks/useWebSocket.ts'],
            technology: 'React + Zustand',
            description: 'Routes incoming ServerMessages to the appropriate Zustand stores based on message kind. Handles graph.full, graph.update, event, session.state, pipeline.full, and other message types.',
          },
          {
            id: 'event-store',
            label: 'Event Store',
            blockType: 'transform',
            files: ['packages/client/src/stores/event-store.ts'],
            technology: 'Zustand',
            description: 'Accumulates AVP events for the current session. Provides filtered views by category and type. Clears on session reattach when eventCount resets to zero.',
          },
          {
            id: 'graph-store',
            label: 'Graph Store',
            blockType: 'transform',
            files: ['packages/client/src/stores/graph-store.ts'],
            technology: 'Zustand',
            description: 'Manages the codebase graph (nodes, edges, groups), file heat values, activity indicators, session-touched files, and pipeline layer data. Drives both the codebase map and pipeline view.',
          },
          {
            id: 'session-store',
            label: 'Session Store',
            blockType: 'transform',
            files: ['packages/client/src/stores/session-store.ts'],
            technology: 'Zustand',
            description: 'Tracks active session metadata: attached pane, connection status, session ID, agent state (idle/working/waiting), and tmux pane list for the session picker UI.',
          },
          {
            id: 'force-layout',
            label: 'Force Layout Engine',
            blockType: 'transform',
            files: [
              'packages/client/src/components/CodebaseMap/ForceLayout.ts',
              'packages/client/src/components/CodebaseMap/useForceGraph.ts',
            ],
            technology: 'D3-force simulation',
            description: 'Runs a d3-force simulation to position file nodes using charge repulsion, link attraction, and group clustering forces. Outputs positioned SimNode[] arrays consumed by the canvas renderer.',
          },
          {
            id: 'map-renderer',
            label: 'Canvas Map Renderer',
            blockType: 'sink',
            files: ['packages/client/src/components/CodebaseMap/MapRenderer.ts'],
            technology: 'Canvas2D',
            description: 'Renders the codebase map on a Canvas2D surface with pan/zoom, semantic zoom tiers (container → module → file), heat glow effects, group hulls, file indicators, and hit-testing for click/hover interactions.',
          },
          {
            id: 'timeline-render',
            label: 'Timeline Component',
            blockType: 'sink',
            files: ['packages/client/src/components/Timeline/Timeline.tsx'],
            technology: 'React + Canvas',
            description: 'Renders a vertical timeline of AVP events with color-coded category icons, expandable detail rows, and auto-scroll to the latest event. Provides the chronological view of agent activity.',
          },
        ],
        edges: [
          { id: 'e1', source: 'ws-client', target: 'store-dispatch', label: 'ServerMessage', edgeType: 'data' },
          { id: 'e2', source: 'store-dispatch', target: 'event-store', label: 'AVPEvent', edgeType: 'data' },
          { id: 'e3', source: 'store-dispatch', target: 'graph-store', label: 'graph.full / graph.update', edgeType: 'data' },
          { id: 'e4', source: 'store-dispatch', target: 'session-store', label: 'session.state', edgeType: 'data' },
          { id: 'e5', source: 'graph-store', target: 'force-layout', label: 'nodes, edges, groups', edgeType: 'data' },
          { id: 'e6', source: 'force-layout', target: 'map-renderer', label: 'positioned SimNode[]', edgeType: 'data' },
          { id: 'e7', source: 'event-store', target: 'timeline-render', label: 'AVPEvent[]', edgeType: 'data' },
        ],
      },

      // --- Pipeline 3: Steering Command Flow ---
      {
        id: 'steering-flow',
        label: 'Steering Command Flow',
        category: 'request-handling',
        description: 'User interactions in the frontend are translated into steering commands sent via WebSocket to the server, which forwards them as tmux send-keys to the agent terminal.',
        blocks: [
          {
            id: 'user-interaction',
            label: 'User Interaction',
            blockType: 'source',
            files: [
              'packages/client/src/components/CodebaseMap/CodebaseMap.tsx',
              'packages/client/src/components/SteeringBar/SteeringBar.tsx',
            ],
            technology: 'React event handlers',
            description: 'Captures user steering actions: right-click chat prompts on the codebase map, approve/reject buttons for permission prompts, text input via the terminal prompt bar, and pause/resume/cancel controls.',
          },
          {
            id: 'ws-send',
            label: 'WebSocket Send',
            blockType: 'transform',
            files: ['packages/client/src/ws/ws-client.ts'],
            technology: 'Browser WebSocket',
            description: 'Serializes steering commands into ClientMessage JSON frames and sends them over the WebSocket connection. Command types include prompt, approve, reject, pause, resume, cancel, focus_file, and scope_boundary.',
          },
          {
            id: 'command-handler',
            label: 'Command Handler',
            blockType: 'transform',
            files: ['packages/server/src/ws/command-handler.ts'],
            technology: 'Fastify WebSocket',
            description: 'Receives ClientMessage commands from the WebSocket and translates them into tmux terminal operations. Maps prompt → typed text + Enter, approve → "y" + Enter, pause → Ctrl+C, etc.',
          },
          {
            id: 'tmux-send',
            label: 'tmux send-keys',
            blockType: 'sink',
            files: ['packages/server/src/pty/agent-process.ts'],
            technology: 'tmux send-keys',
            description: 'Executes tmux send-keys to type text and keystrokes into the agent\'s terminal pane. Handles special keys (Enter, Ctrl+C, Escape) and text escaping for safe injection into the tmux session.',
          },
        ],
        edges: [
          { id: 'e1', source: 'user-interaction', target: 'ws-send', label: 'SteeringCommand', edgeType: 'data' },
          { id: 'e2', source: 'ws-send', target: 'command-handler', label: 'ClientMessage', edgeType: 'data' },
          { id: 'e3', source: 'command-handler', target: 'tmux-send', label: 'text + keystrokes', edgeType: 'data' },
        ],
      },
    ],
  };
}
